# Generated by Django 4.2.7 on 2023-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='mark_as_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
